Description: Creates VPC and required components of VPC

Parameters:
  ProjectName:
    Type: String
    Description: Project Name
  Environment:
    Type: String
    Description: Environment Name
  VPCCIDR:
    Type: String
    Description: CIDR block should be used to create the VPC (e.g. 192.168.0.0/24)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 192.168.0.0/24)

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-VPC"

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-IGW"

  GatewayToInternet:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-PublicRouteTable"

  PrivateRouteTable1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-PrivateRouteTable1"

  PrivateRouteTable2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-PrivateRouteTable2"

  PublicRoute:
    Type: "AWS::EC2::Route"
    DependsOn: GatewayToInternet
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTable

  
Outputs:
  VPCID:
    Description: "VPC ID"
    Value: !Ref VPC
    
  PublicRouteTable:
    Description: "Public Route Table ID"
    Value: !Ref PublicRouteTable
  
  PrivateRouteTable1:
    Description: "Private Route Table #1 ID"
    Value: !Ref PrivateRouteTable1

  PrivateRouteTable2:
    Description: "Private Route Table #2 ID"
    Value: !Ref PrivateRouteTable2